[package]
name = "moving-square"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.28"  
winit = "0.29"
pollster = "0.4"
glam = "0.32"
bytemuck = { version = "1.22", features = ["derive"] }
encase = "0.12"
log = "0.4"
env_logger = "0.11"
